
previews:
  generation: automatic

services:
  - type: web
    runtime: ruby
    name: todos-api-service
    repo: https://github.com/vincetse/todos-api
    numInstances: 1
    region: oregon
    plan: free
    branch: main
    buildCommand: bundle install
    #preDeployCommand: rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    autoDeployTrigger: checksPass
    #maxShutdownDelaySeconds: 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 5
      - key: RAILS_MAX_THREADS
        value: 1
      - key: SECRET_TOKEN
        generateValue: true

databases:
  - name: todos-api-db
    postgresMajorVersion: 16
    region: oregon
    plan: free
    databaseName: db
