name: Docker Images
on: [push, pull_request]
jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build images
        run: docker buildx build
               --push
               --platform linux/arm/v6,linux/arm64/v8,linux/amd64
               --rm -t docker.pkg.github.com/vincetse/todos-api/app
               .

      - name: Inspect images
        run: docker buildx imagetools inspect docker.pkg.github.com/vincetse/todos-api/app:latest
